import Head from "next/head";
import { useForm } from "react-hook-form";
import Image from "next/image";
import axios from "axios";

export default function Create() {
  const { register, handleSubmit } = useForm();

  const onSubmit = (data) => {
    axios
      .post(
        "https://saison-app-api.herokuapp.com/api/v1/posts",
        {
          title: data.title,
          body: data.body,
          url: data.url[0],
        },
        {
          headers: {
            "content-type": "multipart/form-data",
          },
        }
      )
      .then((res) => {
        console.log(res);
      });
    console.log(data);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <h1>ログイン</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label htmlFor="title">title</label>
            <input id="title" {...register("title")} />
          </div>
          <div>
            <label htmlFor="body">body</label>
            <input id="body" {...register("body")} />
          </div>
          <div>
            <label htmlFor="url">image</label>
            <input id="url" {...register("url")} type="file" />
          </div>
          <button type="submit">ログイン</button>
        </form>
      </div>
    </>
  );
}
