import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";
import clsx from "clsx";
import TimelineItem from "../components/TimelineItem";
import { withAuthServerSideProps } from "../lib/auth";

const inter = Inter({ subsets: ["latin"] });

const classes = {
  base: "text-gray-600 py-2 px-4 block focus:outline-none font-medium w-1/2",
  selected: "",
  timeline: "",
  ranking: "",
  notTimeline: "",
  notRanking: "",
  notSelected: "border-b-4",
};

export const getServerSideProps = withAuthServerSideProps("/api/v1/posts");

export default function Index(props) {
  const posts = props;
  const [tabIndex, setTabIndex] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Tabs
          selectedIndex={tabIndex}
          onSelect={(index) => setTabIndex(index)}
          selectedTabClassName="bg-black"
        >
          <TabList className="flex mb-0 list-none flex-wrap pt-3 flex-row">
            <Tab
              className={clsx([
                classes.base,
                "saison-blue text-white rounded-t-lg",
                tabIndex === 0 ? classes.timeline : classes.notTimeline,
              ])}
            >
              タイムライン
            </Tab>
            <Tab
              className={clsx([
                classes.base,
                "saison-green text-white rounded-t-lg",
                tabIndex === 1 ? classes.selected : classes.notRanking,
              ])}
            >
              ランキング
            </Tab>
          </TabList>

          <TabPanel className="saison-blue">
            <div className="pt-4">
              {posts.data.map((post) => {
                return <TimelineItem post={post} key={post.id} />;
              })}
            </div>
          </TabPanel>
          <TabPanel className="saison-green">
            <div className="pt-4">
              {posts.data.map((post) => {
                return <TimelineItem post={post} key={post.id} />;
              })}
            </div>
          </TabPanel>
        </Tabs>
      </div>
    </>
  );
}

// export async function getServerSideProps() {
//   const res = await fetch(`https://saison-app-api.herokuapp.com/api/v1/posts`);
//   const posts = await res.json();
//   console.log(posts.data);
//   return { props: { posts } };
// }
