import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";
import clsx from "clsx";
import TimelineItem from "../components/TimelineItem";

const inter = Inter({ subsets: ["latin"] });

const classes = {
  base: "text-gray-600 py-2 px-4 block focus:outline-none font-medium w-1/2",
  selected: "border-t-4",
  notSelected: "border-b-4",
};

export default function Index({ posts }) {
  const [tabIndex, setTabIndex] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Tabs
          selectedIndex={tabIndex}
          onSelect={(index) => setTabIndex(index)}
          selectedTabClassName="bg-black"
        >
          <TabList className="flex mb-0 list-none flex-wrap pt-3 flex-row">
            <Tab
              className={clsx([
                classes.base,
                tabIndex === 0 ? classes.selected : classes.notSelected,
              ])}
            >
              タイムライン
            </Tab>
            <Tab
              className={clsx([
                classes.base,
                tabIndex === 1 ? classes.selected : classes.notSelected,
              ])}
            >
              ランキング
            </Tab>
          </TabList>

          <TabPanel className="bg-black">
            <div>
              <h1>POST一覧</h1>
              {posts.data.map((post) => {
                return <TimelineItem post={post} key={post.id} />;
              })}
            </div>
          </TabPanel>
          <TabPanel>
            <h2>Any content 2</h2>
          </TabPanel>
        </Tabs>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://saison-app-api.herokuapp.com/api/v1/posts`);
  const posts = await res.json();
  console.log(posts.data);
  return { props: { posts } };
}
